spring:
  application:
    name: GDSC-UET
  data:
    mongodb:
      uri: mongodb+srv://gdscuet2024:pqU8QJezpBMvqfy8@cluster0.xdniv.mongodb.net/
      database: gdsc_uet_service
server:
  port: 8080
  servlet:
    context-path: /api/v1


